name: finsent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.0.1           # Apple M2 (MPS) build
  - numpy=1.24.4
  - scipy=1.11.0
  - scikit-learn=1.3.0
  - pandas=2.3.1
  - scikit-image
  - numba=0.61.2
  - llvmlite=0.44.0
  - spacy=3.8.7
  - pip
  - pip:
    - transformers==4.30.2
    - shap==0.42.1
    - lime==0.2.0.1
    - huggingface-hub==0.34.3
    - tqdm
    - PyYAML
    - regex
    - slicer==0.0.7
    - cloudpickle
